#!/usr/bin/env bash
# Script that configures a new web server

# Variables
index="/var/www/html/index.html"
url_youtube="https://www.youtube.com/watch?v=QH2-TGUlwu4"
available_default="/etc/nginx/sites-available/default"
error404="/usr/share/nginx/html/404.html"
newline2="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"


# Update
sudo apt-get -y update
sudo apt-get -y upgrade

# Install nginx
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Permission
sudo chown -R "$USER":"$USER" /var/

# html files
echo "Hello World" | sudo tee $index
echo "Ceci n'est pas une page" | sudo tee $error404

# Redirects
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $url_youtube permanent;" $available_default

# Page 404
sudo sed -i "/listen 80 default_server/a error_page 404 /error404.html;" $available_default

# Header
sudo sed -i "s|server_name\ _;|$newline2|" $available_default


# Starts Nginx
sudo service nginx start
