#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "
frontend http
	bind *:80
	mode http
	default_backend web-backend
	backend web-backend
balance roundrobin
	server 3312-web-01 35.237.0.179:80 check
	server 3312-web-02 54.167.64.127:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
