#!/usr/bin/env bash
# Configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

path="/etc/haproxy/haproxy.cfg"
echo "
frontend http
	bind *:80
	mode http
	default_backend icap_pool
backend icap_pool
	balance roundrobin
	mode http
	server 3312-web-01 35.237.0.179:80 check
	server 3312-web-02 54.167.64.127:80 check" | sudo tee -a $path > /dev/null

sudo service haproxy start
sudo service nginx restart
