#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with while and if
COUNTER=1
while [ $COUNTER -le 10 ]; do
    echo Best School

    if [ $COUNTER -eq 9 ]
    then
	echo Hi
    fi
    let COUNTER+=1
done
