#!/usr/bin/env bash
# This script is displaying numbers 1 to 20 using case
i=1
while [ $i -lt 21 ]
do
    case $i in
    5)
        echo "bad luck from China"
        ;;
    10)
        echo "bad luck from Japan"
        ;;
    18)
        echo "bad luck from Italy"
        ;;
    esac
        echo $i
    ((i++))
done
