#!/usr/bin/env bash
# This script is a clock with while
h=0
while [ $h -lt 13 ]
do
    m=1
    echo "Hour: $h"
    while [ $m -lt 60 ]
    do
        echo $m
        ((m++))
    done
    ((h++))
done
